spring.application.name=amanat-backend

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.data.mongodb.uri=mongodb://localhost:27017/amanat
spring.data.mongodb.database=amanat

server.port=8080
http://localhost:8080/oauth2/authorization/google

spring.security.oauth2.client.registration.google.client-id=767617053982-tbaqhhn26l97uhapknc3ikstapas6tj8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo